/*
 *
 * Product constants
 *
 */

export const CREATE = "CREATE";
export const UPDATE = "UPDATE";
export const DELETE = "DELETE";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_ALL_PRODUCTS_REQUEST = "FETCH_ALL_PRODUCTS_REQUEST";
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAILl";
export const PRODUCT_SEARCH_CHANGE = "PRODUCT_SEARCH_CHANGE";
export const PRODUCT_SUGGESTIONS_FETCH_REQUEST =
  "PRODUCT_SUGGESTIONS_FETCH_REQUEST";
export const PRODUCT_SUGGESTIONS_CLEAR_REQUEST =
  "PRODUCT_SUGGESTIONS_CLEAR_REQUEST";

export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
/*
 *
 * User constants
 *
 */
export const ACCOUNT_FORMDATA_CLEAR = "ACCOUNT_FORMDATA_CLEAR";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const FETCH_ALL_USERS_REQUEST = "FETCH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const USER_LOGOUT = "USER_LOGOUT";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const SET_SIGNUP_FORM_ERRORS = "SET_SIGNUP_FORM_ERRORS";
export const SET_LOGIN_FORM_ERRORS = "SET_LOGIN_FORM_ERRORS";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";

/*
 *
 * Cart constants
 *
 */

export const ADD_TO_CARD = "ADD_TO_CARD";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

/*
 *
 * Order constants
 *
 */

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";

export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";

export const ORDER_CREATE_FAILURE = "ORDER_CREATE_FAILURE";

export const ORDER_USER_LIST_SUCCESS = "ORDER_USER_LIST_SUCCESS";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";

export const ORDER_ALL_LIST_SUCCESS = "ORDER_ALL_LIST_SUCCESS";
export const ORDER_ALL_LIST_UPDAT = "ORDER_ALL_LIST_UPDAT";

export const ORDER_LIST_FAILURE = "ORDER_LIST_FAILURE";

export const ORDER_SEARCH_SUCCESS = "ORDER_SEARCH_SUCCESS";

/*
 *
 * Wishlist constants
 *
 */
export const FETCH_WISHLIST_REQUEST = "FETCH_WISHLIST_REQUEST";
export const FETCH_WISHLIST = "FETCH_WISHLIST";

/*
 *
 * Review constants
 *
 */

export const REVIEW_CHANGE = "REVIEW_CHANGE";
export const SET_REVIEW_FORM_ERRORS = "SET_REVIEW_FORM_ERRORS";

export const FETCH_REVIEWS_REQUEST = "FETCH_REVIEWS_REQUEST";

export const RESET_REVIEW = "export const";

export const FETCH_PRODUCT_REVIEWS = "FETCH_PRODUCT_REVIEWS";
export const FETCH_MY_REVIEWS = "FETCH_MY_REVIEWS";
export const ADD_REVIEW = "ADD_REVIEW";
export const REMOVE_REVIEW = "REMOVE_REVIEW";
export const SET_REVIEWS_LOADING = "SET_REVIEWS_LOADING";
export const FETCH_REVIEWS = "FETCH_REVIEWS";
export const UPDATE_REVIEW = "UPDATE_REVIEW";

/*
 *
 * Account constants
 *
 */
export const FETCH_PROFILE = "FETCH_PROFILE";
export const ACCOUNT_INFO_CHANGE = "USER_INFO_CHANGE";
export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const DELET_PROFILE_INFO = "DELET_PROFILE_INFO";

/*
 *
 * Category constants
 *
 */

export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAILURE = "CATEGORY_CREATE_FAILURE";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAILURE = "CATEGORY_DELETE_FAILURE";

export const CATEGORIES_FETCH_REQUEST = "CATEGORIES_FETCH_REQUEST";
export const CATEGORIES_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS";
export const CATEGORIES_FETCH_FAILURE = "CATEGORY_FETCH_FAILURE";

//modal

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
