/*
 *
 * Product constants
 *
 */

export const CREATE = "CREATE";
export const UPDATE = "UPDATE";
export const DELETE = "DELETE";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_ALL_PRODUCTS_REQUEST = "FETCH_ALL_PRODUCTS_REQUEST";
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAILl";

/*
 *
 * User constants
 *
 */
export const ACCOUNT_FORMDATA_CLEAR = "ACCOUNT_FORMDATA_CLEAR";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const FETCH_ALL_USERS_REQUEST = "FETCH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const USER_LOGOUT = "USER_LOGOUT";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

/*
 *
 * Cart constants
 *
 */

export const ADD_TO_CARD = "ADD_TO_CARD";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

/*
 *
 * Order constants
 *
 */

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";

export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";

export const ORDER_CREATE_FAILURE = "ORDER_CREATE_FAILURE";

export const ORDER_USER_LIST_SUCCESS = "ORDER_USER_LIST_SUCCESS";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";

export const ORDER_ALL_LIST_SUCCESS = "ORDER_ALL_LIST_SUCCESS";

export const ORDER_LIST_FAILURE = "ORDER_LIST_FAILURE";

/*
 *
 * Wishlist constants
 *
 */
export const FETCH_WISHLIST_REQUEST = "FETCH_WISHLIST_REQUEST";
export const FETCH_WISHLIST = "FETCH_WISHLIST";

/*
 *
 * Review constants
 *
 */

export const REVIEW_CHANGE = "REVIEW_CHANGE";
export const SET_REVIEW_FORM_ERRORS = "SET_REVIEW_FORM_ERRORS";

export const FETCH_REVIEWS_REQUEST = "FETCH_REVIEWS_REQUEST";

export const RESET_REVIEW = "export const";

export const FETCH_PRODUCT_REVIEWS = "FETCH_PRODUCT_REVIEWS";
export const FETCH_MY_REVIEWS = "FETCH_MY_REVIEWS";
export const ADD_REVIEW = "ADD_REVIEW";
export const REMOVE_REVIEW = "REMOVE_REVIEW";
export const SET_REVIEWS_LOADING = "SET_REVIEWS_LOADING";
export const FETCH_REVIEWS = "FETCH_REVIEWS";

/*
 *
 * Account constants
 *
 */
export const FETCH_PROFILE = "FETCH_PROFILE";
export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";
export const ACCOUNT_INFO_CHANGE = "USER_INFO_CHANGE";
